window.BAKERY_PRODUCTS = [
  {
    id: "customizable-cake",
    name: "Unicorn Cake",
    image: "assets/products/blacked out bgm/1. customizable 900 rs .png",
    description: "Handcrafted eggless cake finished with premium cream and carefully designed for memorable celebrations. Freshly baked using quality ingredients and decorated by hand for every order.",
    price: "Starting at Rs. 900",
    weights: ["Size confirmed on WhatsApp"],
    category: "signature",
    occasion: "Custom celebrations",
    bestFor: "Designer themes and premium celebration tables",
    themeLine: "Perfect for bespoke celebrations with a refined handcrafted finish.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize colours, message, theme, and finishing details according to your celebration.",
    featured: true
  },
  {
    id: "customized-princess-bday-cake",
    name: "Customized Princess Birthday Cake",
    image: "assets/products/blacked out bgm/2. customized princess bday cake , price 900 rs 1kg .png",
    description: "A charming eggless princess-themed cake made for birthdays and joyful childhood celebrations. Carefully decorated by hand with a polished finish for a memorable party table.",
    price: "Starting at Rs. 750",
    weights: ["1kg"],
    category: "signature",
    occasion: "Birthday",
    bestFor: "Children's birthdays and fairytale celebrations",
    themeLine: "Perfect for birthdays and joyful celebrations.",
    themeLine: "Princess birthday cake specially created for children and fairytale celebrations. Customization is Available according to your preference.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize colours, name, age, message, and theme details according to your preference.",
    featured: true
  },
  {
    id: "special-3kg-cake",
    name: "Special 3kg Cake",
    image: "assets/products/blacked out bgm/3. 3kg , 2700rs .png",
    description: "A premium eggless celebration cake designed for larger gatherings and special occasions. Freshly prepared after confirmation and finished with care for an elegant presentation.",
    price: "Starting at Rs. 2700",
    weights: ["3kg"],
    category: "wedding-anniversary",
    occasion: "Large celebrations",
    bestFor: "Family gatherings and premium custom themes",
    themeLine: "Designed for elegant occasions and larger celebration moments.",
    preparation: "24 to 36 hours",
    servings: "12 to 24 servings",
    customisation: "Customize theme, colours, message, and occasion styling after order confirmation.",
    featured: true
  },
  {
    id: "butterfly-black-current-bluberry-cake",
    name: "Butterfly Blackcurrant Blueberry Cake",
    image: "assets/products/blacked out bgm/butterfly black current bluberry cake .png",
    description: "A handcrafted eggless blueberry-inspired cake with a graceful butterfly theme. Freshly baked and decorated by hand for birthdays, surprises, and elegant celebrations.",
    price: "Price on request",
    weights: ["Size confirmed on WhatsApp"],
    category: "birthday",
    occasion: "Elegant celebrations",
    bestFor: "Creative themes, floral details, and boutique styling",
    themeLine: "Butterfly-themed blueberry cake designed for soft, elegant celebrations.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize the message, colour tone, and butterfly styling as per your occasion.",
    featured: false
  },
  {
    id: "butterfly-red-rose-cake",
    name: "Butterfly Red Rose Cake",
    image: "assets/products/blacked out bgm/butterfly red rose cake 1kg 750rs.png",
    description: "An elegant eggless cake with red rose accents and butterfly-inspired detailing. Made fresh for every order and finished with a polished celebration look.",
    price: "Starting at Rs. 750",
    weights: ["1kg"],
    category: "birthday",
    occasion: "Romantic celebrations",
    bestFor: "Anniversaries, surprises, and rose-themed occasions",
    themeLine: "Red rose butterfly cake for romantic celebrations and special surprises.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize flowers, message, colours, and finishing details according to your preference.",
    featured: false
  },
  {
    id: "butterscotch-cake",
    name: "Butterscotch Cake",
    image: "assets/products/blacked out bgm/butterscotch 1kg 750rs .png",
    description: "A freshly baked eggless butterscotch cake with a smooth premium cream finish. Handcrafted for birthdays, anniversaries, and simple family celebrations.",
    price: "Starting at Rs. 750",
    weights: ["1kg"],
    category: ["signature", "birthday"],
    occasion: "Everyday celebrations",
    bestFor: "Birthdays, family moments, and simple celebrations",
    themeLine: "Classic butterscotch cake with a clean handcrafted finish.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize message, occasion theme, and simple decor details.",
    featured: false
  },
  {
    id: "butterscotch-coffee-mocha-cake",
    name: "Butterscotch Coffee Mocha Cake",
    image: "assets/products/blacked out bgm/butterscotch coffee mocha price 750 1kg.png",
    description: "A premium eggless cake balancing butterscotch, coffee, and mocha-inspired notes. Freshly baked and decorated by hand for celebrations with a richer flavour profile.",
    price: "Starting at Rs. 750",
    weights: ["1kg"],
    category: ["signature", "birthday"],
    occasion: "Premium celebrations",
    bestFor: "Coffee lovers and refined flavour preferences",
    themeLine: "Coffee mocha butterscotch cake for a refined celebration flavour.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize the message, occasion styling, and finishing details.",
    featured: false
  },
  {
    id: "buttterscotch-cake",
    name: "Butterscotch Cake Premium",
    image: "assets/products/blacked out bgm/buttterscotch 1kg 850rs.png",
    description: "A premium eggless butterscotch cake prepared fresh after order confirmation. Carefully finished with cream and hand decoration for a memorable celebration.",
    price: "Starting at Rs. 850",
    weights: ["1kg"],
    category: "wedding-anniversary",
    occasion: "Family celebrations",
    bestFor: "Classic birthdays and handcrafted butterscotch cakes",
    themeLine: "Premium butterscotch cake for birthdays and family occasions.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize colours, message, and occasion details according to your preference.",
    featured: false
  },
  {
    id: "custom-luxury-cake-one",
    name: "Custom Luxury Cake One",
    image: "assets/products/blacked out bgm/ChatGPT Image Jun 30, 2026, 07_25_13 PM.png",
    description: "A handcrafted eggless custom cake finished with premium cream and thoughtful decoration. Designed for celebrations where presentation and freshness both matter.",
    price: "Price on request",
    weights: ["Size confirmed on WhatsApp"],
    category: "signature",
    occasion: "Custom celebrations",
    bestFor: "Luxury styling and creative celebration themes",
    themeLine: "Custom luxury cake styling for memorable celebrations.",
    preparation: "24 to 36 hours",
    servings: "4 to 10 servings",
    customisation: "Customize theme, colour palette, name, message, and finishing details.",
    featured: false
  },
  {
    id: "custom-luxury-cake-two",
    name: "Hello Kitty Cake",
    image: "assets/products/blacked out bgm/ChatGPT Image Jun 30, 2026, 08_00_40 PM.png",
    description: "A premium eggless cake made fresh and styled by hand for special occasions. Each order is confirmed before preparation to maintain quality and freshness.",
    price: "Price on request",
    weights: ["Size confirmed on WhatsApp"],
    category: "signature",
    occasion: "Custom celebrations",
    bestFor: "Elegant handcrafted cakes and bespoke themes",
    themeLine: "Custom handcrafted cake for elegant celebration moments.",
    preparation: "24 to 36 hours",
    servings: "4 to 10 servings",
    customisation: "Customize the occasion, message, theme, and decorative finish.",
    featured: false
  },
  {
    id: "customized-cricket-cake",
    name: "Customized Cricket Cake",
    image: "assets/products/blacked out bgm/customized cricket cake 1kg 900rs.png",
    description: "A sporty handcrafted eggless cake designed for cricket lovers and birthday celebrations. Freshly baked and decorated by hand for a fun themed celebration.",
    price: "Starting at Rs. 900",
    weights: ["1kg"],
    category: "signature",
    occasion: "Birthday",
    bestFor: "Cricket fans, kids' themes, and sporty celebrations",
    themeLine: "Cricket-themed cake specially made for sports fans and birthday parties.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize player name, age, colours, message, and cricket theme details.",
    featured: false
  },
  {
    id: "customized-blueberry-3kg-cake",
    name: "Customized Blueberry 3kg Cake",
    image: "assets/products/blacked out bgm/customized rates , 3kg blueberry 2500rs .png",
    description: "A special eggless blueberry cake designed for larger celebrations and family gatherings. Freshly baked after confirmation and finished with a premium handcrafted look.",
    price: "Starting at Rs. 2500",
    weights: ["3kg"],
    category: "wedding-anniversary",
    occasion: "Large celebrations",
    bestFor: "Blueberry lovers and custom celebration themes",
    themeLine: "Large blueberry celebration cake for gatherings and custom themes.",
    preparation: "24 to 36 hours",
    servings: "12 to 24 servings",
    customisation: "Customize theme, message, colours, and decorative finish according to your preference.",
    featured: false,
    bestSeller: true
  },
  {
    id: "doreamon-butterscotch-cake",
    name: "Doraemon Butterscotch Cake",
    image: "assets/products/blacked out bgm/doreamon ; buttersctoch , 1kg - 850.png",
    description: "A playful eggless butterscotch cake inspired by a loved cartoon theme. Made fresh and hand decorated for children's birthdays and surprise celebrations.",
    price: "Starting at Rs. 850",
    weights: ["1kg"],
    category: "signature",
    occasion: "Birthday",
    bestFor: "Children's birthdays and cartoon-themed celebrations",
    themeLine: "Doreamon-inspired butterscotch cake specially made for children.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize name, age, colours, and character-inspired theme details.",
    featured: false
  },
  {
    id: "pineapple-cake",
    name: "Pineapple Cake",
    image: "assets/products/blacked out bgm/pineapple , 1kg 750 .png",
    description: "A fresh eggless pineapple cake with a light premium cream finish. Handcrafted for simple, bright, and memorable celebration moments.",
    price: "Starting at Rs. 750",
    weights: ["1kg"],
    category: "wedding-anniversary",
    occasion: "Fresh celebrations",
    bestFor: "Simple birthdays, family gatherings, and light flavours",
    themeLine: "Classic pineapple cake for fresh and cheerful celebrations.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize message, colour accents, and occasion styling.",
    featured: false
  },
  {
    id: "pista-pann-musical-theme-cake",
    name: "Pista Paan Musical Theme Cake",
    image: "assets/products/blacked out bgm/pista pann flavour cakes musical theam custom'.png",
    description: "A handcrafted eggless pista paan-inspired cake with a musical theme finish. Freshly baked and styled for unique celebrations with a personalized touch.",
    price: "Price on request",
    weights: ["Size confirmed on WhatsApp"],
    category: "birthday",
    occasion: "Creative celebrations",
    bestFor: "Musical themes and unique custom cake concepts",
    themeLine: "Musical theme cake with pista paan flavour inspiration.",
    preparation: "24 to 36 hours",
    servings: "4 to 10 servings",
    customisation: "Customize musical details, message, colours, and theme accents.",
    featured: false
  },
  {
    id: "rasmalai-cake",
    name: "Rasmalai Cake",
    image: "assets/products/blacked out bgm/rasmalai 850 rs 1kg .jpg",
    description: "A premium eggless rasmalai cake inspired by festive Indian flavours. Freshly prepared and decorated by hand for birthdays, family occasions, and celebrations.",
    price: "Starting at Rs. 850",
    weights: ["1kg"],
    category: "signature",
    occasion: "Festive celebrations",
    bestFor: "Family occasions and Indian festive flavour preferences",
    themeLine: "Rasmalai cake for festive celebrations and family moments.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize message, festive styling, and finishing details.",
    featured: false,
    bestSeller: true
  },
  {
    id: "strawberry-cake",
    name: "Strawberry Cake",
    image: "assets/products/blacked out bgm/strawberry , 850 -1kg.png",
    description: "A freshly baked eggless strawberry cake with a soft premium cream finish. Handcrafted for birthdays, surprises, and bright celebration moments.",
    price: "Starting at Rs. 850",
    weights: ["1kg"],
    category: "signature",
    occasion: "Soft celebrations",
    bestFor: "Birthdays, surprises, and fresh strawberry cakes",
    themeLine: "Strawberry cake for soft, cheerful, and elegant celebrations.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize colour accents, message, and occasion details.",
    featured: false
  },
  {
    id: "strawberry-half-kg-cake",
    name: "Butterfly Strawberry Cake",
    image: "assets/products/blacked out bgm/strawberry 1kg - 1000 , 12 kg 500 .png",
    description: "A premium eggless strawberry cake available for smaller and standard celebration sizes. Freshly prepared after confirmation and finished with careful hand decoration.",
    price: "Starting at Rs. 500",
    weights: ["500g", "1kg"],
    category: "birthday",
    occasion: "Small celebrations",
    bestFor: "Intimate moments and fresh strawberry cake orders",
    themeLine: "Strawberry cake available for intimate and family celebrations.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize message, size, colour accents, and celebration styling.",
    featured: false
  },
  {
    id: "truffle-cake",
    name: "Truffle Cake",
    image: "assets/products/blacked out bgm/truffle cake price 1kg 850rs.png",
    description: "A rich eggless truffle cake with a smooth chocolate-inspired finish. Freshly baked and hand decorated for birthdays, anniversaries, and indulgent celebrations.",
    price: "Starting at Rs. 850",
    weights: ["1kg"],
    category: "signature",
    occasion: "Chocolate celebrations",
    bestFor: "Chocolate lovers, birthdays, and indulgent occasions",
    themeLine: "A handcrafted favourite loved by chocolate enthusiasts.",
    themeLine: "Chocolate truffle cake for rich and elegant celebration moments.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize message, chocolate finish, theme, and occasion details.",
    featured: false,
    bestSeller: true
  },
  {
    id: "vanilla-cake-750",
    name: "Vanilla Cake",
    image: "assets/products/blacked out bgm/vanilla 1kg 750rs.png",
    description: "A classic eggless vanilla cake with a clean premium cream finish. Freshly baked and decorated by hand for birthdays, anniversaries, and simple celebrations.",
    price: "Starting at Rs. 750",
    weights: ["1kg"],
    category: "signature",
    occasion: "Classic celebrations",
    bestFor: "Timeless birthdays and elegant minimal cakes",
    themeLine: "Classic vanilla cake for timeless celebration moments.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize message, colours, and simple decor according to your preference.",
    featured: false
  },
  {
    id: "vanilla-cake-850",
    name: "Premium Vanilla Cake",
    image: "assets/products/blacked out bgm/vanilla 1kg 850rs.png",
    description: "A premium eggless vanilla cake prepared fresh for confirmed orders. Hand finished with elegant cream work for a polished celebration presentation.",
    price: "Starting at Rs. 850",
    weights: ["1kg"],
    category: "wedding-anniversary",
    occasion: "Classic celebrations",
    bestFor: "Premium vanilla cakes with handcrafted styling",
    themeLine: "Premium vanilla cake with handcrafted celebration styling.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize message, colour palette, and occasion styling.",
    featured: false
  },
  {
    id: "vanilla-cake-two",
    name: "Blue Icing Cake",
    image: "assets/products/blacked out bgm/vanilla 2 1kg 750rs.png",
    description: "A freshly baked eggless vanilla cake with handcrafted decoration for every order. Designed for simple, elegant, and memorable celebration moments.",
    price: "Starting at Rs. 750",
    weights: ["1kg"],
    category: "signature",
    occasion: "Classic celebrations",
    bestFor: "Simple family moments and vanilla celebration cakes",
    themeLine: "Vanilla celebration cake with a soft premium finish.",
    preparation: "24 hours",
    servings: "4 to 10 servings",
    customisation: "Customize message, name, colours, and finishing details.",
    featured: false
  }
];
